title: Rosa Website

tabs:
  content:
    label: Inhalte
    icon: page
    sections:
      pages:
        type: pages
        status: all

  settings:
    label: Globale Informationen
    icon: cog
    columns:
      main:
        width: 2/3
        sections:
          general:
            type: fields
            fields:
              title:
                type: text
                label: Website-Titel
              Subheadline:
                type: text
                label: Untertitel
              description:
                type: textarea
                label: Beschreibung
                size: medium

      sidebar:
        width: 1/3
        sections:
          social:
            type: fields
            headline: Social Media
            fields:
              facebook:
                type: url
                label: Facebook
              instagram:
                type: url
                label: Instagram
              whatsapp:
                type: url
                label: WhatsApp

          contact:
            type: fields
            headline: Kontaktinformationen
            fields:
              phone:
                type: tel
                label: Telefonnummer
              email:
                type: email
                label: E-Mail-Adresse
              address:
                type: textarea
                label: Adresse
                size: small

          openingHours:
            label: Öffnungszeiten
            type: fields
            fields:
              opening_hours:
                type: textarea
                label: Öffnungszeiten
                size: large
                placeholder: |
                  Montag: 11:30 - 14:30 & 17:30 - 23:00
                  Dienstag: 11:30 - 14:30 & 17:30 - 23:00
                  Mittwoch: 11:30 - 14:30 & 17:30 - 23:00
                  Donnerstag: 11:30 - 14:30 & 17:30 - 23:00
                  Freitag: 11:30 - 14:30 & 17:30 - 24:00
                  Samstag: 11:30 - 14:30 & 17:30 - 24:00
                  Sonntag: 12:00 - 22:00
                help: "Geben Sie die Öffnungszeiten für jeden Wochentag ein. Eine Zeile pro Tag."

          # colors:
          #   type: fields
          #   headline: Design-Farben
          #   fields:
          #     primary_color:
          #       type: text
          #       label: Primärfarbe (Kupfer)
          #       placeholder: "#d4a574"
          #       help: Hauptfarbe für Buttons und Akzente
          #       width: 1/2
          #     secondary_color:
          #       type: text
          #       label: Sekundärfarbe (Anthrazit)
          #       placeholder: "#3d4142"
          #       help: Farbe für Texte und Header
          #       width: 1/2
          #     accent_color:
          #       type: text
          #       label: Akzentfarbe (Rostrot)
          #       placeholder: "#8b4a42"
          #       help: Zusätzliche Akzentfarbe
          #       width: 1/2
          #     bg_warm:
          #       type: text
          #       label: Warmer Hintergrund
          #       placeholder: "#f7f3f0"
          #       help: Warme Hintergrundfarbe für Sektionen
          #       width: 1/2
