title: Restaurant Website

buttons:
  - open
  - preview
  - content-translator # Re-order the button as needed
  - languages

tabs:
  content:
    label: Inhalte
    icon: page
    sections:
      pages:
        type: pages
        status: all

  settings:
    label: Einstellungen
    icon: cog
    columns:
      main:
        width: 2/3
        sections:
          general:
            type: fields
            fields:
              title:
                type: text
                label: Website-Titel
              tagline:
                type: text
                label: Untertitel
              description:
                type: textarea
                label: Beschreibung
                size: medium

      sidebar:
        width: 1/3
        sections:
          colors:
            type: fields
            headline: Design-Farben
            fields:
              primary_color:
                type: text
                label: Primärfarbe (Kupfer)
                placeholder: "#d4a574"
                help: Hauptfarbe für Buttons und Akzente
                width: 1/2
              secondary_color:
                type: text
                label: Sekundärfarbe (Anthrazit)
                placeholder: "#3d4142"
                help: Farbe für Texte und Header
                width: 1/2
              accent_color:
                type: text
                label: Akzentfarbe (Rostrot)
                placeholder: "#8b4a42"
                help: Zusätzliche Akzentfarbe
                width: 1/2
              bg_warm:
                type: text
                label: Warmer Hintergrund
                placeholder: "#f7f3f0"
                help: Warme Hintergrundfarbe für Sektionen
                width: 1/2
          social:
            type: fields
            headline: Social Media
            fields:
              facebook:
                type: url
                label: Facebook
              instagram:
                type: url
                label: Instagram
              twitter:
                type: url
                label: Twitter
